apiVersion: v1
kind: Pod
metadata:
  name: nodehelloworld.example.com
  labels:
    apps: helloworld
spec:
  containers:
  - name: k8-demo
    image: arjunachari12/k8s-demo
    ports: 
    - name: nodejs-port
      containerPort: 3000
